// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tvt_231230930_de01.Models;

#nullable disable

namespace tvt_231230930_de01.Migrations
{
    [DbContext(typeof(Tvt_231230930_de01Context))]
    [Migration("20251024013731_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tvt_231230930_de01.Models.TvtComputer", b =>
                {
                    b.Property<int>("tvtComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tvtComId"));

                    b.Property<string>("tvtComImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tvtComName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tvtComStatus")
                        .HasColumnType("bit");

                    b.Property<decimal>("tvtComprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("tvtComId");

                    b.ToTable("TvtComputer");
                });
#pragma warning restore 612, 618
        }
    }
}
