// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvtDay10LabCf.Models;

#nullable disable

namespace TvtDay10LabCf.Migrations
{
    [DbContext(typeof(TvtDay10LabCfContext))]
    partial class TvtDay10LabCfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TvtDay10LabCf.Models.TvtLoai_San_Pham", b =>
                {
                    b.Property<long>("tvtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tvtId"));

                    b.Property<string>("tvtMaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tvtTenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tvtTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("tvtId");

                    b.ToTable("TvtLoai_San_Pham");
                });

            modelBuilder.Entity("TvtDay10LabCf.Models.TvtSan_Pham", b =>
                {
                    b.Property<long>("tvtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tvtId"));

                    b.Property<long>("TvtLoai_San_PhamtvtId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tvtDonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tvtHinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tvtMaLoai")
                        .HasColumnType("bigint");

                    b.Property<string>("tvtMaSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tvtSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("tvtTenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tvtTrangThai")
                        .HasColumnType("bit");

                    b.HasKey("tvtId");

                    b.HasIndex("TvtLoai_San_PhamtvtId");

                    b.ToTable("TvtSan_Pham");
                });

            modelBuilder.Entity("TvtDay10LabCf.Models.TvtSan_Pham", b =>
                {
                    b.HasOne("TvtDay10LabCf.Models.TvtLoai_San_Pham", "TvtLoai_San_Pham")
                        .WithMany("TvtSan_Phams")
                        .HasForeignKey("TvtLoai_San_PhamtvtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TvtLoai_San_Pham");
                });

            modelBuilder.Entity("TvtDay10LabCf.Models.TvtLoai_San_Pham", b =>
                {
                    b.Navigation("TvtSan_Phams");
                });
#pragma warning restore 612, 618
        }
    }
}
